### PR TITLE
Add license property to package.json

### PR DESCRIPTION
**Pull request by bengourley**
npm quit yo' complainin'!

`npm WARN package.json schemata@2.4.0 No license field.`

### CODE REVIEW

**Comment by serby** [comment]
@domharrington sold me on ISC  

https://en.wikipedia.org/wiki/ISC_license

**Comment by bengourley** [comment]
Well you have BSD clause 3 in the readme, so that's the one I referenced.

**Comment by bengourley** [comment]
My bad, BSD 2 clause is linked

**Comment by bengourley** [comment]
Do you want to update that to ISC?

**Comment by serby** [comment]
I think a slow move over to ISC is probably the way we will end up, so
might as well.

On 30 October 2015 at 13:58, Ben Gourley <notifications@github.com> wrote:

> Do you want to update that to ISC?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serby/schemata/pull/33#issuecomment-152532742>.
>



-- 

paul.serby@clock.co.uk
Chief Technology Officer


*Mobile: +44 7881 550999**Skype: paul.serby*
*Twitter: serby*
--


* <http://www.clock.co.uk/>*

The Old School HouseBridge Road, Hunton Bridge,Kings Langley, WD4 8RQ
Switchboard: +44 1923 261166www.clock.co.uk


* <http://twitter.com/clock>    <https://github.com/clocklimited>
<http://www.linkedin.com/company/clock-limited>
<http://www.clock.co.uk/blog>*

*www.clock.co.uk/email-disclaimer <http://www.clock.co.uk/email-disclaimer>*
*clock.® is a Registered Trademark of Clock Limited in the European
Community and other territories*

**Comment by bengourley** [comment]
@serby I've updated both license references to ISC, as per your newer modules.

**Comment by serby** [comment]
:+1:

**Pull request merged**
